---
title: "Untitled"
author: "satsuki gyoten"
date: "2023-09-13"
output: html_document
---
1-1
```{r}
applications<- read.csv("applications.csv")

```

1-2
```{r}
head(applications)

```

1-3
```{r}
## The independent variable(treatment variable) is the criminal history, and the dependent variable(outcome variable) is the whether one will receive a call back for a job interview. The control variable is race. We observe whether criminal history affects the likelihood of receiving a call back.

```

1-4
```{r}
## The first and the second (1,2) are counted as one observation.The person at the top of the table applied for job1 (the same job as the second person above), has no criminal record, is white, and received a return call.The second person applied for job1, has criminal record, is white, and received a return call.

```

1-5
```{r}
## job_id:numeric_nonbinary
##criminal:numeric_binary
##race:character
##call:numeric_binary

```

1-6
```{r}
dim(applications)
##696observations
```

2-1
```{r}
dim(applications)
## 696 observations in the original data frame

dim(applications_white)
## 300 in the new data frame
```
##[applications$race=="white",] what is the last comma?

2-2
```{r}
mean(applications_white$criminal)
0.5
## People with criminal record and people without criminal record are properly split half half within the observation
```

2-3
```{r}
mean(applications_white$call)
0.2533333
## 25.3% received  the call

```


2-4
```{r}
##a treatment variable:criminal
##b outcome variable:call

```

2-5
```{r}
##a treatment group: a set of observations with criminal=1
##b control group: a set of observations with criminal=0

```

```{r}
## find the percentage of people with criminal=1 who have Call=1

applications_white_crime<- applications_white[applications_white$criminal ==1,]
summary(applications_white_crime)

```

3-2
```{r}
##Within this experiment, 16.67% of whites with a criminal background received a return call.
```

3-3
```{r}
applications_white_noncrime<- applications_white[applications_white$criminal ==0,]
summary(applications_white_noncrime)

##Within this experiment, 34% of whites without criminal background received a return call.
```

```{r}
##The estimated mean causal effect of having a criminal record on the probability of receiving a call back for a job interview is 12.54965%. The assumption is that having a criminal record reduces the probability of receiving a call back. This is because it is reasonable to assume that employers would want employers who do not cause crime or other social problems. The treatment is the observation with criminal cases and the outcome is the observation with returned calls. The results are as follows. The direction of the mean treatment effect is the same as the hypothesis, and the unit of measurement:both variables are binominal.

##I ran the codes below:

applications_crime<- applications[applications$criminal==1,]
percentage_crime<- mean(applications_crime$call)

applications_noncrime<- applications[applications$criminal==0,]
percentage_noncrime<- mean(applications_noncrime$call)

comparison<- percentage_noncrime-percentage_crime
comparison*100


```
what is the unit of measurement

