---
title: "A5 HW"
author: "satsuki gyoten"
date: "2023-10-24"
output: html_document
---
10.9 exercise

1

Why do people move toward elections the more they feel the eyes of others on them?

Assumption: People want to be trusted by those around them. Feeling the eyes of others refers to the situation where one's actions are being watched by others.
Model: People who want to be trusted by those around them will move toward the more they feel the eyes of others on them.
Hypotheses:
When comparing the case where neighbors can know whether a person went to the polls or not (A) and the case where they cannot know (B), those who fall into the former case (A) have a higher voter turnout.

2
Frequency distribution:frequency count that have a certain value.
Relative frequency distribution:frequency proportion that have a certain value.

3
This is because PDF is basically about the theoretical probability but relative frequency distribution is basically about sample distribution.

4
PMF uses a discrete type of random variable to indicate the probability of a random variable taking a particular value (for example, a dice experiment).
On the other hand, CDF indicates the probability of a random variable taking less than a specific value, and can be applied to continuous or discrete random variables, and this CDF is integrated to find the probability from one value to another.

5
When comparing whether Republican or Democratic supporters are more likely to vote. For example, a contingency table can be created with 1 Republican supporter and 0 Democrat supporter/ 1 who goes to the polls and 1 who does not.

6
Bernoulli distribution: the process by which it rains on election day
Poisson distribution: A process in which a resident in Japan do not have the right to vote

7
Sorry, I can't find the designated experimental site, as the website has been redesigned.

8
What I checked: Japan's working population
What I found: Data from 1975 to 2019 shows an increase of roughly 20 million people. / The increase is a flat steady increase.
selecting a co variable:Japan's population
what I found: There was a similar trend between the two/ However,the gap between the population and the working population is wider today than in the past.

9
3^4/ e^3*4! =0.1680314
```{r}
x<- exp(1)^3*factorial(4)
3^4/ x
```

10
1)
Let B be the event of going to Bach, S the event of going to Stravinsky, T the event of meeting with friends, and A the event of appreciating the music alone.

The utilities for going to Bach are
EU(B)=p(B)*U(BT)+p(notB)*U(BA)
=0.5*(10+8)+0.5*(10-2)
=13
The utility for going to Stravinsky is
EU(S)=p(S)*U(BT)+p(notS)*U(BA)
=0.5*(5+8)+0.5*(5-2)
=8

Therefore,the woman should head to Bach concert.

2)
EU(B)=p(B)*U(BT)+p(notB)*U(BA)
=0.3*(10+8)+0.7*(10-2)
=11

EU(S)=p(S)*U(BT)+p(notS)*U(BA)
=0.7*(5+8)+0.3*(5-2)
=10
Therefore,the woman should head to Bach concert.

11
set events as follows
S:B is stronger
W:B is weaker
O: maneuver were observed

When A decides to star a war, there are 2 consequences, winning and losing.

probability to lose
P(lose)= P(S|O)=P(O|S)P(S)/ P(O)=4/7
therefore, EU(lose)=4/7*(-1)= -4/7
probability to win
P(win)= P(W|O)=P(O|W)P(W)/ P(O)=4/7
therefore, EU(lose)=3/7*1=3/7
EU(stay)=0

The Expected Utility in total is -4/7+3/7+0=-1/7.
Therefore, A should not start a war when it observed maneuvers.



11.4 exercise
1
This is because PDF is basically about the theoretical probability but relative frequency distribution is basically about sample distribution.

2
PMF uses a discrete type of random variable to indicate the probability of a random variable taking a particular value (for example, a dice experiment). On the other hand,CDF indicates the probability of a random variable taking less than a specific value, and can be applied to continuous or discrete random variables.


3
A probability density function (pdf) is the derivative of a cumulative distribution function (cdf). 

4
joint distribution of GDP and intelligence

5
A normal distribution means that when a sample of size n is randomly selected from a population with population mean μ and population variance σ^2, the sample mean X approximately follows N(μ,σ^2/n) when n is large. The reason it is not clear whether the distribution follows a normal distribution just by looking at it is that it is not clear whether it actually follows this definition.

6
PDF is basically about the theoretical probability. On the other hand,relative frequency distribution is basically about sample distribution.

7
It is because PDF PDF shows a continuous rather than a discrete probability distribution.

8
