---
title: "final"
author: "satsuki gyoten"
date: "2023-12-10"
output: html_document
---
```{r}

library(dplyr) # install this package if you don't have it yet
library(ggplot2) # install this package if you don't have it yet
library(grDevices) # install this package if you don't have it yet
library(grid)
library(tidyr) # I don't think you absolutely need this library
library(broom) # I don't think you absolutely need this library

rm(list=ls())
```

```{r}
library(readr)
cq_data <- read_csv("cq_data.csv")
```
#1
```{r}
nationalization <- function(dv, dvp){
  -sd(dv- dvp, na.rm = T)
}
```

#2
```{r}
swing_variance <- cq_data %>%
  filter(inc3 !=0) %>%
  group_by(year) %>%
  summarise(nationalization = nationalization(dv, dvp)
  ) %>%
  ungroup()

show(swing_variance)
```

```{r}
library(readr)
gary_j_data <- read_csv("gary_j_data.csv")
```

```{r}
measure_comparison <- gary_j_data %>%
  filter(year>=1954) %>%
  group_by(year) %>%
  summarise(nationalization1 = nationalization(dv, dvp), # our measure
            nationalization2 = cor(dv,dpres,use = "pairwise.complete.obs") # garyj's measure
            )

cor(measure_comparison$nationalization1, measure_comparison$nationalization2,method = "pearson")
```
0.79


# Calculate Incumbency advantage  coeffients by year
# Join these estimates with our nationalization measure
```{r}
b_incumbency_adv <- cq_data %>%
  group_by(year) %>% 
  do(., tidy(lm(dv ~ dvp + ptynow + inc3, data = . ))) %>% 
  filter(term == "inc3") %>%
  ungroup() %>% 
  left_join(., swing_variance, by="year") %>% # join to nationalization measure
  mutate(post_1952 = as.numeric(year>1952)) 
```

```{r}
b_incumbency_adv$marker_break <- NA
b_incumbency_adv$marker_break[b_incumbency_adv$year==1950] <- 1950
b_incumbency_adv$marker_break[b_incumbency_adv$year==1954] <- 1954
```

```{r}
nationalization_year_plot <- ggplot(data=swing_variance, 
                                    aes(x= year, y= nationalization)) +
  geom_line() +
  geom_point() +
  theme_bw() + ylab("Nationalization") + xlab("Year")

nationalization_year_plot 
```

```{r}
incumbency_adv_year_plot <- ggplot(data=b_incumbency_adv, 
                                   aes(x=year, y=estimate)) +
  geom_line() +
  geom_point() +
  theme_bw() + ylab("Incumbency Advantage") + xlab("Year")

incumbency_adv_year_plot
```

```{r}
#6a
#pre 1952
b_incumbency_adv %>%
  filter(post_1952 ==0 ) %>%
  summarise(correlation = cor(estimate, nationalization, method ="pearson"))

#post 1952
b_incumbency_adv %>%
  filter(post_1952 ==1 ) %>%
  summarise(correlation = cor(estimate, nationalization, method ="pearson"))
```

```{r}
#6b
#pre 1952
b_incumbency_adv %>%
  filter(post_1952 ==0 ) %>%
  summarise(correlation = cor(estimate, nationalization, method ="spearman"))

#post 1952
b_incumbency_adv %>%
  filter(post_1952 ==1 ) %>%
  summarise(correlation = cor(estimate, nationalization, method ="spearman"))

```

```{r}
nationalization_incumbency_path_plot <- ggplot(data=b_incumbency_adv, 
                                               aes(x=nationalization, 
                                                   y=estimate))+ 
  geom_point(aes(colour= year)) +
  geom_path(aes(color=year))+
  geom_text(size=4.5, aes(color=year, label=marker_break, hjust=-.3, vjust=.2)) +
  geom_text(label= "Post 1952:",
            x=-11, y=10.7, size=4.5, fontface="bold") +
  geom_text(label= "Pre 1952:",
            x=-11.5, y=4.8, size=4.5,fontface="bold") +
  theme_classic() + 
  xlab("Nationalization") + 
  ylab("Incumbency Advantage") +
  scale_color_continuous(name="Year") +
  xlim(c(-13.5,-2.5)) +
  theme(legend.key.height = unit(1.5, "cm"),
        legend.title.align=0)

nationalization_incumbency_path_plot

```


```{r}
#1
#a yes it will.
#b yes it will.

original <- function(x) {
     x*10^3
} 

income_kilo<- c(1,2,3)
income_original<- original(income_kilo)

#c
mean(income_kilo)
mean(income_original)

var(income_kilo)
var(income_original)


```
```{r}
#2
#a 0.38- 0.302= 0.078
7.8%

#b
df <- data.frame(x = rnorm(1000))
df$dummyT<- NA
df$dummyT[1:380]<-1
df$dummyT[381:1000]<-0

df$dummyC<- NA
df$dummyC[1:302]<-1
df$dummyC[303:1000]<-0


se<- sqrt(sd(df$dummyT)^2/1000+sd(df$dummyC)^2/1000)

#c
mean<- 0.38 - 0.302

#i
mean+1.64*se
mean-1.64*se
# population mean should be 11.3% to 4.3%

#ii
mean+1.96*se
mean-1.96*se
# population mean should be 11.9% to 3.7%

#d
mean/se
# this is around 3.9 >1.96  reject

```

```{r}
#a 0.76


set.seed(178974)
sims <- 300
reach <- c("Y","N")
event <- 0

for(i in 1:sims){
  sample1 <- sample(x = reach, size = 1, 
         replace = T, prob = c(0.76, 0.24))
  if(sample1[1] == "Y"){
    event <- event + 1
  }
}

answer <- event/sims
answer
```

```{r}
#b 0.76*0.76= 0.5776
set.seed(178974)
sims <- 300
reach <- c("Y","N")
event <- 0

for(i in 1:sims){
  sample1 <- sample(x = reach, size = 2, 
         replace = T, prob = c(0.76, 0.24))
  if(sample1[1] == "Y" & sample1[2] == "Y"){
    event <- event + 1
  }
}

answer <- event/sims
answer
```

```{r}
#c
0.99

set.seed(178974)
sims <- 300
reach <- c("Y","N")
event <- 0

for(i in 1:sims){
  for(j in 1:5){
    sample <- sample(x = reach, size = 1, 
           replace = T, prob = c(0.76, 0.24))
    if(sample[1] == "Y"){
      event <- event + 1
      break
    }
  }
}

answer <- event/sims
answer


```

```{r}
#a
#null hypothesis: In local level, incumbents' vote share and challengers' vote share is the same.
#research hypothesis: In local level, incumbents have higher vote advantage than challengers.

#b
```

