---
title: "Untitled"
author: "satsuki gyoten"
date: "2023-10-4"
output: html_document
---
```{r}

ccap <- read.csv("CCAP.csv")
View(ccap)


gay <- read.csv("gay.csv")
View(gay)

head(ccap, n=4)
head(gay, n=4)

dim(gay)
dim(ccap)

```
Evidence of Data Fabricaion

```{r}
hist(ccap$feel,freq = F, breaks = 10)

hist(gay$feel1,freq = F, breaks = 10)


```
1.
Yes, they are similar.

```{r}
summary(ccap$feel)
sd(ccap$feel)

summary(gay$feel1)
sd(gay$feel1)
```
2.
ccap$feel
mean 58.09
median 52.00
standard deviation 28.40383

gay$feel1
mean 58.63
median 52.00
standard deviation 28.55804

```{r}

```
3.
No, because Los Angeles is one of the most pro-Democratic cities in the US, and therefore the distribution of "Feel" should lean toward the higher end of the scale.

```{r}
control_group <- gay[gay$treatment== "No Contact",]
plot(x=control_group$feel1, y=control_group$feel2)
plot(x=control_group$feel1, y=control_group$feel3)
plot(x=control_group$feel1, y=control_group$feel4)
```
4. yes

```{r}
cor(control_group$feel1, control_group$feel2, use = "complete.obs")
cor(control_group$feel1, control_group$feel3, use = "complete.obs")
cor(control_group$feel1, control_group$feel4, use = "complete.obs")

```
5.yes


6.yes
