---
title: "B4"
author: "satsuki gyoten"
date: "2023-11-07"
output: html_document
---
1.
```{r}
set.seed(36850) # set random seed so that you get the same output everytime even though it's "random"

sample_space_coin <- c("H", "T")
event_probs_coin <- c(0.5, 0.5)


coin_flip <- function(){
  sample(
    size = 1,
    x = sample_space_coin,
    prob = event_probs_coin,
    replace = TRUE
  )
}

coin_flip()

```
From the code above, we can simulate a coin flip. 
When coin_flip() was called 10 times, the result was A. This shows that the chances of getting each side of the coin are actually about 0.5 each.

2.
```{r}
set.seed(36850)
flip1 <- coin_flip()
flip2 <- coin_flip()
flip3 <- coin_flip()
flip4 <- coin_flip()

# Example flips, they will always be the same because I set a random seed.
flip1 # H
flip2 # T
flip3 # T
flip4 # H

# Function that acts like a random variable.
# returns 1 if flip == "H" and 0 otherwise.

X_coin <- function(flip){
  ifelse(flip == "H",1,0)
}


# The code below should return a 1 for flip1 and flip4 and 0 for flip2 and flip3
X_coin(flip1)
X_coin(flip2)
X_coin(flip3)
X_coin(flip4)
```
3.
Treating `X_coin()` like a random variable describe it:
  a. What is the probability of 1? ->0.5
```{r}
sims<- 10000
event <- 0

for (i in 1:sims) {
orders<- sample(X_coin(flip ))
if(orders==1){
  event<- event+1
}
 }
answer <- event/sims
answer
```
  
  b. What is the probability of 0?
  c. What is the expectation of `X_coin()`?
  d. What is the variance of `X_coin()`?
